services:
  frontend:
    image: production_line:front
    container_name: production_line
    build: ./
    ports:
      - "${PORT}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
